name = "ontologySeparation"
version = "0.1.0"
defaultTargets = ["OntologySeparation"]

[[require]]
name = "QIT"
git = "https://github.com/QuAIR/Lean-QIT.git"
rev = "c1d59b133b56e3d79efb11ee46a728d290f761f5"

[[lean_lib]]
name = "OntologySeparation"
moreLeanArgs = ["-DautoImplicit=false"]

[[lean_lib]]
name = "Tests"
moreLeanArgs = ["-DautoImplicit=false"]
