import OntologySeparation.Experiments.ForcedSignalingAccessibleOptimum
import OntologySeparation.Operational.VCausalFiniteSupport
import OntologySeparation.Experiments.ForcedSignalingPhysicalMain
import OntologySeparation.Experiments.ForcedSignalingTimingExtension
import OntologySeparation.Experiments.ForcedSignalingAccessible
import OntologySeparation.Experiments.ForcedSignalingVCausalCompletions
import OntologySeparation.Experiments.ForcedSignalingVCausal
import OntologySeparation.Operational.VCausalAssumptions
import OntologySeparation.Signaling
import OntologySeparation.Certificates.ForcedSignaling
import OntologySeparation.PartialEnvironment
import OntologySeparation.Statistics
import OntologySeparation.Experiments.EnvironmentDiscrimination
import OntologySeparation.Experiments.RecordEnvironment
import OntologySeparation.Experiments.LFReadout
import OntologySeparation.Experiments.LFJoint
import OntologySeparation.Experiments.LFAgencyRelaxation
import OntologySeparation.Experiments.LFAgencyRelaxationDiagnostics
import OntologySeparation.Operational.LFAgencySqrtTwo
import OntologySeparation.Certificates.LFAgencySqrtTwo
import OntologySeparation.Experiments.LFAgencyAngleOptimality
import OntologySeparation.Experiments.LFAssumptionAtlas
import OntologySeparation
import OntologySeparation.Catalog.Matrix
import OntologySeparation.Core.Assumptions
import OntologySeparation.Core.ExactFiniteChecker
import OntologySeparation.Core.AutomaticGrid
import OntologySeparation.Core.SeparatorSearch
import OntologySeparation.Reporting.Search
import OntologySeparation.Core.RegisterAccess
import OntologySeparation.Adapters.NamedFiniteQuantum
import OntologySeparation.Experiments.RecordAccess
import OntologySeparation.Recipes.Separation
import OntologySeparation.Adapters.FiniteCircuit
import OntologySeparation.Experiments.PartialLeakage
import OntologySeparation.Experiments.PartialLeakageRobustness

-- Selected audit roots and their transitive dependencies; not a census of all declarations.
-- Each #export_theorem / #export_scenario also automatically audits its own dependencies.
#print axioms OntologySeparation.RealizedProfileBound.realizable
#print axioms OntologySeparation.RealizedProfileBound.valid
#print axioms OntologySeparation.ClassicalWorld.realizedBound
#print axioms OntologySeparation.Separation.excludes
#print axioms OntologySeparation.Behavior.prob_le_one
#print axioms OntologySeparation.Behavior.mix
#print axioms OntologySeparation.inconsistent_profile
#print axioms OntologySeparation.Catalog.bellLocalClaim
#print axioms OntologySeparation.Catalog.bellQuantumClaim
#print axioms OntologySeparation.Catalog.bellPRClaim
#print axioms OntologySeparation.Catalog.lfBoundClaim
#print axioms OntologySeparation.Catalog.lfQuantumClaim
#print axioms OntologySeparation.Catalog.lfControlClaim
#print axioms OntologySeparation.Catalog.echoClaim
#print axioms OntologySeparation.Catalog.leakClaim
#print axioms OntologySeparation.Catalog.phaseClaim
#print axioms OntologySeparation.RealQuantum.probability_born
#print axioms OntologySeparation.RealQuantum.singlet_normalized
#print axioms OntologySeparation.LF.Component.read_charlie
#print axioms OntologySeparation.LF.Component.read_debbie

#print axioms OntologySeparation.Claim.sound
#print axioms OntologySeparation.Catalog.matrix
#print axioms OntologySeparation.Memory.registered_parameters_valid
#print axioms OntologySeparation.quantum_operator_bound
#print axioms OntologySeparation.profileTheory_empty


#print axioms OntologySeparation.Shared.LF_ns_sharp
#print axioms OntologySeparation.Shared.local_three_LF_bound
#print axioms OntologySeparation.Shared.singlet_noSignaling
#print axioms OntologySeparation.Shared.inner_score
#print axioms OntologySeparation.Shared.LF_contamination_required
#print axioms OntologySeparation.Shared.LF_mix_score
#print axioms OntologySeparation.DephasedSinglet.bell_noise_threshold
#print axioms OntologySeparation.DephasedSinglet.LF_noise_threshold
#print axioms OntologySeparation.Research.pairwise_consistent
#print axioms OntologySeparation.Research.triangle_mixture_bound
#print axioms OntologySeparation.Research.random_query_bound
#print axioms OntologySeparation.Research.passive_relabel
#print axioms OntologySeparation.Research.joint_recovery
#print axioms OntologySeparation.Research.phase_state_normalized
#print axioms OntologySeparation.Research.phase_state_entangled
#print axioms OntologySeparation.Research.noisy_order_probability
#print axioms OntologySeparation.Research.public_error_bound
#print axioms OntologySeparation.free_binary_extension
#print axioms OntologySeparation.ProfileBridge.excludes
#print axioms OntologySeparation.Bound.excluded_by_lower

#print axioms OntologySeparation.Research.phase_state_not_complex_product
#print axioms OntologySeparation.Research.real_randomized_recovery

#print axioms OntologySeparation.Shared.LF_NS_contamination_attained
#print axioms OntologySeparation.Shared.LF_NS_fraction_required
#print axioms OntologySeparation.Shared.saturating_is_LF
#print axioms OntologySeparation.OperationalBell.chsh_bound
#print axioms OntologySeparation.OperationalBell.singlet_excludes
#print axioms OntologySeparation.FriendRecords.probability_preserved
#print axioms OntologySeparation.FriendRecords.bound
#print axioms OntologySeparation.FriendRecords.singlet_excludes
#print axioms OntologySeparation.Qubit.twice_dephased
#print axioms OntologySeparation.Qubit.phase_then_dephase
#print axioms OntologySeparation.Qubit.hadamard_twice
#print axioms OntologySeparation.Qubit.density_invariants
#print axioms OntologySeparation.Channel.andThen_assoc
#print axioms OntologySeparation.Countermodels.signaling_score
#print axioms OntologySeparation.Countermodels.signaling_not_local
#print axioms OntologySeparation.Countermodels.dependent_score
#print axioms OntologySeparation.Countermodels.dependent_not_independent
#print axioms OntologySeparation.Qubit.protected_dephasing
#print axioms OntologySeparation.OperationalProfiles.bell_bound
#print axioms OntologySeparation.OperationalProfiles.lf_bound
#print axioms OntologySeparation.OperationalProfiles.bell_supported_count
#print axioms OntologySeparation.OperationalProfiles.lf_supported_count
#print axioms OntologySeparation.ClassicalWorld.chsh_bound
#print axioms OntologySeparation.ClassicalWorld.cannot_reproduce_singlet
#print axioms OntologySeparation.ClassicalWorld.constant_score
#print axioms OntologySeparation.Channel.andThen
#print axioms OntologySeparation.Channel.parallel
#print axioms OntologySeparation.Experiment.same_evolution
#print axioms OntologySeparation.ProfileBound.valid
#print axioms OntologySeparation.ProfileBound.under
#print axioms OntologySeparation.Qubit.dephase

#print axioms OntologySeparation.Countermodels.quantumFriend_not_readable
#print axioms OntologySeparation.Countermodels.rejected_records_realized

#print axioms OntologySeparation.Scenario.ExactPredictions.prediction

#print axioms OntologySeparation.Recipes.probability_correct
#print axioms OntologySeparation.Recipes.probability_bounds
#print axioms OntologySeparation.Recipes.compare

#print axioms OntologySeparation.TwoQubit.Gate.normSq
#print axioms OntologySeparation.TwoQubit.Pure.born
#print axioms OntologySeparation.TwoQubit.Pure.amplitude_normalized
#print axioms OntologySeparation.TwoQubit.State.normalized
#print axioms OntologySeparation.TwoQubit.no_signaling_alice
#print axioms OntologySeparation.TwoQubit.no_signaling_bob
#print axioms OntologySeparation.TwoQubit.chsh_correct
#print axioms OntologySeparation.TwoQubit.excludes_local
#print axioms OntologySeparation.TwoQubit.compare
#print axioms OntologySeparation.TwoQubit.singlet_matches_reference
#print axioms OntologySeparation.TwoQubit.prepare_singlet_circuit

#print axioms OntologySeparation.FriendProtocol.encode_norm
#print axioms OntologySeparation.FriendProtocol.record_agreement
#print axioms OntologySeparation.FriendProtocol.undo_friends
#print axioms OntologySeparation.FriendProtocol.recordZ_encoded
#print axioms OntologySeparation.FriendProtocol.output_norm
#print axioms OntologySeparation.FriendProtocol.pure_normalized
#print axioms OntologySeparation.FriendProtocol.probability_bridge
#print axioms OntologySeparation.LocalFriendlinessRecipe.probability_correct
#print axioms OntologySeparation.LocalFriendlinessRecipe.no_signaling
#print axioms OntologySeparation.LocalFriendlinessRecipe.score_correct
#print axioms OntologySeparation.LocalFriendlinessRecipe.matches_reference
#print axioms OntologySeparation.LocalFriendlinessRecipe.charlie_noise_threshold
#print axioms OntologySeparation.LocalFriendlinessRecipe.coherent_excludes_profile
#print axioms OntologySeparation.LocalFriendlinessRecipe.fully_dephased_realizes_profile

#print axioms OntologySeparation.ExperimentAccess.Separator.not_equivalent

#print axioms OntologySeparation.ExperimentAccess.Equivalent.statistic

#print axioms OntologySeparation.FiniteQuantum.Test.normalized

#print axioms OntologySeparation.FiniteQuantum.Test.prepend_prob

#print axioms OntologySeparation.FiniteQuantum.local_behavior_eq

#print axioms OntologySeparation.RecordAccess.dephased_entry

#print axioms OntologySeparation.RecordAccess.all_local_tests

#print axioms OntologySeparation.RecordAccess.recovery_isometry

#print axioms OntologySeparation.RecordAccess.coherent_recovery

#print axioms OntologySeparation.RecordAccess.dephased_recovery

#print axioms OntologySeparation.RecordAccess.joint_not_equivalent

#print axioms OntologySeparation.FiniteModels.score_mixture

#print axioms OntologySeparation.FiniteModels.compatible_bound

#print axioms OntologySeparation.FiniteModels.Exclusion.excludes

#print axioms OntologySeparation.FiniteModels.no_conflicting_certificates

#print axioms OntologySeparation.ModelCompatibility.passes_one_bound_but_excluded

#print axioms OntologySeparation.ModelCompatibility.coherent_excludes_dephased_class

#print axioms OntologySeparation.ModelCompatibility.recordBoundClaim


-- Automatic exact comparison and finite-intervention trust roots.
#print axioms OntologySeparation.ExactFinite.equivalent_iff_exact
#print axioms OntologySeparation.ExactFinite.domainAgreementOfExact
#print axioms OntologySeparation.ExactFinite.CheckedResult.sound
#print axioms OntologySeparation.RecipeSeparation.outcomeProbability_correct
#print axioms OntologySeparation.RecipeSeparation.coherenceSeparator
#print axioms OntologySeparation.RecipeSeparation.expandedSeparator
#print axioms OntologySeparation.FiniteQuantum.measureAfterIsometry_prob_eq_lift
#print axioms OntologySeparation.FiniteCircuit.Circuit.apply_cons
#print axioms OntologySeparation.FiniteCircuit.test_normalized


-- Automatically derived finite-family coverage roots.
#print axioms OntologySeparation.ExactFinite.mem_entriesForProtocol
#print axioms OntologySeparation.ExactFinite.entry_protocol_mem


-- Mechanistic partial-leakage showcase roots.
#print axioms OntologySeparation.PartialLeakage.recovery_probability
#print axioms OntologySeparation.PartialLeakage.sequential_attenuation
#print axioms OntologySeparation.PartialLeakage.recovery_gap


-- Continuous partial-leakage robustness roots.
#print axioms OntologySeparation.PartialLeakage.realGap_positive_iff
#print axioms OntologySeparation.PartialLeakage.exact_gap_eq_realGap
#print axioms OntologySeparation.PartialLeakage.wigner_exposure_lt_friend


#print axioms OntologySeparation.PartialLeakage.real_channel_gap
#print axioms OntologySeparation.PartialLeakage.zero_visibility_law
#print axioms OntologySeparation.PartialLeakage.zero_recovery_law

-- Exact finite LF operational correspondence and constructive non-implication.
#print axioms OntologySeparation.LFAssumptionAtlas.operational_iff_lf
#print axioms OntologySeparation.LFAssumptionAtlas.outcome_independence_not_required
#print axioms OntologySeparation.LFAssumptionAtlas.quantum_excludes_operational

#print axioms OntologySeparation.LFJoint.conditional_reconstruct
#print axioms OntologySeparation.LFJoint.conditional_probability
#print axioms OntologySeparation.LFJoint.local_iff_conditional
#print axioms OntologySeparation.LFJoint.joint_iff_lf
#print axioms OntologySeparation.LFJoint.bound
#print axioms OntologySeparation.LFJoint.quantum_excluded

#print axioms OntologySeparation.LFReadout.response_bound
#print axioms OntologySeparation.LFReadout.joint_bound
#print axioms OntologySeparation.LFReadout.sharp_total_budget
#print axioms OntologySeparation.LFReadout.required_mismatch
#print axioms OntologySeparation.LFReadout.quantum_required_error
#print axioms OntologySeparation.LFReadout.mismatchA_remote
#print axioms OntologySeparation.LFReadout.mismatchB_remote
#print axioms OntologySeparation.LFReadout.budgetClaim
#print axioms OntologySeparation.LFReadout.attainingClaim
#print axioms OntologySeparation.LFReadout.exclusionClaim
-- Finite separator-search trust roots.
#print axioms OntologySeparation.ExactFinite.search
#print axioms OntologySeparation.ExactFinite.SearchResult.report

-- Named-register policy and record-access trust roots.
#print axioms OntologySeparation.RegisterAccess.allowed_mono
#print axioms OntologySeparation.RegisterAccess.allowed_full
#print axioms OntologySeparation.RegisterAccess.allowed_empty_iff
#print axioms OntologySeparation.RegisterAccess.not_allowed_of_missing
#print axioms OntologySeparation.RecordAccess.systemOnly_allowed_iff
#print axioms OntologySeparation.RecordAccess.fullRegisterAccess_allowed
#print axioms OntologySeparation.RecordAccess.named_locally_equivalent
#print axioms OntologySeparation.RecordAccess.namedSeparator
#print axioms OntologySeparation.RecordAccess.named_joint_not_equivalent

-- Typed two-register quantum adapter trust roots.
#print axioms OntologySeparation.FiniteQuantum.Named.left_allowed_iff
#print axioms OntologySeparation.FiniteQuantum.Named.both_allowed
#print axioms OntologySeparation.FiniteQuantum.Named.left_equivalent

-- External finite-LP feasibility spike; no physical representation theorem claimed.
#print axioms OntologySeparation.ForcedSignaling.dual_feasible
#print axioms OntologySeparation.ForcedSignaling.bound
#print axioms OntologySeparation.ForcedSignaling.zeroBudget
#print axioms OntologySeparation.ForcedSignaling.zeroBudget_score

-- Physical response model, LP correspondence, sharp optimum and adopter contracts.
#print axioms OntologySeparation.HiddenInfluence.Model.behavior
#print axioms OntologySeparation.HiddenInfluence.strategy_output
#print axioms OntologySeparation.HiddenInfluence.Model.fromStrategies
#print axioms OntologySeparation.HiddenInfluence.Model.toLP
#print axioms OntologySeparation.HiddenInfluence.lp_score
#print axioms OntologySeparation.HiddenInfluence.no_signaling_B
#print axioms OntologySeparation.HiddenInfluence.no_signaling_C
#print axioms OntologySeparation.HiddenInfluence.Sharp.score_exact
#print axioms OntologySeparation.HiddenInfluence.Sharp.signaling_exact
#print axioms OntologySeparation.HiddenInfluence.sharp_tradeoff
#print axioms OntologySeparation.HiddenInfluence.coefficient_optimal
#print axioms OntologySeparation.SharpOptimum.sound
#print axioms OntologySeparation.SignalingStudy.Study.boundClaim
#print axioms OntologySeparation.SignalingStudy.Study.attainmentClaim
#print axioms OntologySeparation.SignalingStudy.Study.signalingClaim
#print axioms OntologySeparation.RecordEnvironment.copyEnvironment_isometry
#print axioms OntologySeparation.RecordEnvironment.preparation_is_copy
#print axioms OntologySeparation.RecordEnvironment.collapsed_entry
#print axioms OntologySeparation.RecordEnvironment.laboratory_state
#print axioms OntologySeparation.RecordEnvironment.same_laboratory_state
#print axioms OntologySeparation.RecordEnvironment.every_laboratory_test
#print axioms OntologySeparation.RecordEnvironment.laboratory_equivalent
#print axioms OntologySeparation.RecordEnvironment.global_states_differ

#print axioms OntologySeparation.QuantumDiscrimination.every_test
#print axioms OntologySeparation.QuantumDiscrimination.attained
#print axioms OntologySeparation.QuantumDiscrimination.same_state_error
#print axioms OntologySeparation.QuantumDiscrimination.strict_improvement
#print axioms OntologySeparation.RecordEnvironment.laboratory_error
#print axioms OntologySeparation.RecordEnvironment.full_error_bound
#print axioms OntologySeparation.RecordEnvironment.full_optimum_attained
#print axioms OntologySeparation.RecordEnvironment.full_beats_laboratory
#print axioms OntologySeparation.RecordEnvironment.return_coherent
#print axioms OntologySeparation.RecordEnvironment.return_collapsed
#print axioms OntologySeparation.RecordEnvironment.returnSeparator

#print axioms OntologySeparation.FiniteShot.prefix_zero
#print axioms OntologySeparation.FiniteShot.prefix_nonneg
#print axioms OntologySeparation.FiniteShot.prefix_bound
#print axioms OntologySeparation.FiniteShot.false_rejection_bound
#print axioms OntologySeparation.FiniteShot.power_bound
#print axioms OntologySeparation.FiniteShot.prefix_point
#print axioms OntologySeparation.FiniteShot.always_failure_null
#print axioms OntologySeparation.FiniteShot.always_success_alternative
#print axioms OntologySeparation.FiniteShot.Plan.rejects_iff
#print axioms OntologySeparation.FiniteShot.Plan.valid
#print axioms OntologySeparation.FiniteShot.Plan.riskClaim
#print axioms OntologySeparation.ReturnStatistics.calibrated_null
#print axioms OntologySeparation.ReturnStatistics.recovery_power
#print axioms OntologySeparation.ReturnStatistics.calibrated_valid
#print axioms OntologySeparation.ReturnStatistics.powerClaim

#print axioms OntologySeparation.FiniteShot.Plan.rejectionProbability_eq
#print axioms OntologySeparation.FiniteShot.Plan.false_rejection_control

#print axioms OntologySeparation.QuantumDiscrimination.error_eq_probability_gap
#print axioms OntologySeparation.QuantumDiscrimination.probability_gap_le
#print axioms OntologySeparation.PartialEnvironment.coherent_entry
#print axioms OntologySeparation.PartialEnvironment.distance_exact
#print axioms OntologySeparation.PartialEnvironment.every_test_bound
#print axioms OntologySeparation.PartialEnvironment.resolves_iff
#print axioms OntologySeparation.PartialEnvironment.no_test_resolves
#print axioms OntologySeparation.PartialEnvironment.optimal_error
#print axioms OntologySeparation.PartialEnvironment.no_fragment_test
#print axioms OntologySeparation.PartialEnvironment.uniform_threshold
#print axioms OntologySeparation.PartialEnvironment.worst_case
#print axioms OntologySeparation.PartialEnvironment.Study.uniformly_resolves

-- Structured adversary-search trust roots.
#print axioms OntologySeparation.AdversarySearch.satisfies_mono
#print axioms OntologySeparation.AdversarySearch.MinimalCore.deletion_necessary
#print axioms OntologySeparation.AdversarySearch.MinimalCore.erase_not_excluding

-- Local-Agency relaxation with unread friend records.
#print axioms OntologySeparation.LFAgencyRelaxation.bound
#print axioms OntologySeparation.LFAgencyRelaxation.quantum_gap
#print axioms OntologySeparation.LFAgencyRelaxation.quantum_public_noSignaling
#print axioms OntologySeparation.LFAgencyRelaxation.quantum_excluded
#print axioms OntologySeparation.LFAgencyRelaxation.feasibility
#print axioms OntologySeparation.LFAgencyRelaxation.recordTVAlice_nonnegative
#print axioms OntologySeparation.LFAgencyRelaxation.recordTVBob_nonnegative
#print axioms OntologySeparation.LFAgencyRelaxation.recordTVAlice_zero_of_local
#print axioms OntologySeparation.LFAgencyRelaxation.recordTVBob_zero_of_local
#print axioms OntologySeparation.LFAgencyRelaxation.local_recordRevealedWithin_zero

#print axioms OntologySeparation.OperationalFriendlinessBenchmark.constant_local
#print axioms OntologySeparation.OperationalFriendlinessBenchmark.dropAbsolute_not_absolute
#print axioms OntologySeparation.OperationalFriendlinessBenchmark.dropAgency_not_agency
#print axioms OntologySeparation.OperationalFriendlinessBenchmark.exact_core
#print axioms OntologySeparation.TimelikeFriendliness.response_chsh_le_two
#print axioms OntologySeparation.TimelikeFriendliness.score_as_mean
#print axioms OntologySeparation.TimelikeFriendliness.factorized_chsh_bound
#print axioms OntologySeparation.TimelikeFriendliness.singlet_score_violates_factorized
#print axioms OntologySeparation.TimelikeFriendliness.unitModel_score
#print axioms OntologySeparation.TimelikeOperationalCore.correlator_base
#print axioms OntologySeparation.TimelikeOperationalCore.score_base
#print axioms OntologySeparation.TimelikeOperationalCore.chsh_bound
#print axioms OntologySeparation.TimelikeOperationalCore.dropStable_score
#print axioms OntologySeparation.TimelikeOperationalCore.dropAlice_score
#print axioms OntologySeparation.TimelikeOperationalCore.dropBob_score
#print axioms OntologySeparation.TimelikeOperationalCore.exact_minimal_core
#print axioms OntologySeparation.TimelikeBellCollapse.outcomeProb_nonneg
#print axioms OntologySeparation.TimelikeBellCollapse.productResponse_noSignaling
#print axioms OntologySeparation.TimelikeBellCollapse.productResponse_outcomeIndependent
#print axioms OntologySeparation.TimelikeBellCollapse.response_score
#print axioms OntologySeparation.TimelikeBellCollapse.score_preserved
#print axioms OntologySeparation.TimelikeBellCollapse.embeds_screening_off
#print axioms OntologySeparation.CausalOrderAdversary.zGate_norm
#print axioms OntologySeparation.CausalOrderAdversary.xGate_norm
#print axioms OntologySeparation.CausalOrderAdversary.fixed_order_mimics_current_statistic
#print axioms OntologySeparation.CausalOrderAdversary.no_input_separates
#print axioms OntologySeparation.CausalOrderAdversary.definite_order_countermodel
#print axioms OntologySeparation.CausalOrderTwoSetting.xxMinus_zero
#print axioms OntologySeparation.CausalOrderTwoSetting.old_setting_still_mimicked
#print axioms OntologySeparation.CausalOrderTwoSetting.xx_setting_separates
#print axioms OntologySeparation.CausalOrderTwoSetting.two_setting_not_equivalent
#print axioms OntologySeparation.CausalOrderUnrestricted.every_scalar_table_mimicked
#print axioms OntologySeparation.CausalOrderUnrestricted.coherent_table_mimicked
#print axioms OntologySeparation.CausalOrderUnrestricted.no_scalar_separator_against_unrestricted
#print axioms OntologySeparation.CausalOrderUnrestricted.two_setting_not_witness_against_unrestricted
#print axioms OntologySeparation.NestedFriendliness.theory_iff_operational
#print axioms OntologySeparation.NestedFriendliness.theory_iff_lf
#print axioms OntologySeparation.NestedFriendliness.quantum_excluded
#print axioms OntologySeparation.NestedFriendliness.depth_invariant
#print axioms OntologySeparation.LocalityFreeFriendliness.antiAB_matches
#print axioms OntologySeparation.LocalityFreeFriendliness.antiBC_matches
#print axioms OntologySeparation.LocalityFreeFriendliness.antiAC_matches
#print axioms OntologySeparation.LocalityFreeFriendliness.shared_and_faithful_impossible
#print axioms OntologySeparation.LocalityFreeFriendliness.locality_free_core_minimal

-- Exact LC4 physical target for forced signaling.
#print axioms OntologySeparation.ForcedSignalingLC4.cluster_normalized
#print axioms OntologySeparation.ForcedSignalingLC4.score_exact
#print axioms OntologySeparation.ForcedSignalingLC4.score_exact_real

-- Exact LC4 hidden-influence witness roots.
#print axioms OntologySeparation.ForcedSignalingLC4Witness.seed_abd_matches
#print axioms OntologySeparation.ForcedSignalingLC4Witness.seed_acd_matches
#print axioms OntologySeparation.ForcedSignalingLC4Witness.model_abd_matches
#print axioms OntologySeparation.ForcedSignalingLC4Witness.model_acd_matches
#print axioms OntologySeparation.ForcedSignalingLC4Witness.tv_exact
#print axioms OntologySeparation.ForcedSignalingLC4Witness.signaling_exact

-- Exact physical forced-signaling Theorem 2 roots.
#print axioms OntologySeparation.ForcedSignalingTheorem2.marginalCoeff_eq_scoreCoeff
#print axioms OntologySeparation.ForcedSignalingTheorem2.marginalScore_eq_score
#print axioms OntologySeparation.ForcedSignalingTheorem2.matches_score
#print axioms OntologySeparation.ForcedSignalingTheorem2.lower_bound
#print axioms OntologySeparation.ForcedSignalingTheorem2.exact_forced_signaling
#print axioms OntologySeparation.ForcedSignalingTheorem2.targetDelta_value


-- Exact sqrt(2) Local-Agency bound and global angle optimization of its witness.
#print axioms OntologySeparation.LFAgencyRelaxation.Correlation.basisCorr_formula
#print axioms OntologySeparation.LFAgencyRelaxation.Correlation.probability_eq_corr
#print axioms OntologySeparation.LFAgencyRelaxation.explicit_quantum_realized
#print axioms OntologySeparation.LFAgencyRelaxation.SqrtTwoCertificate.dual_feasible
#print axioms OntologySeparation.LFAgencyRelaxation.SqrtTwoCertificate.bound
#print axioms OntologySeparation.LFAgencyRelaxation.SqrtTwoPhysical.weighted_difference_le_tv
#print axioms OntologySeparation.LFAgencyRelaxation.SqrtTwoPhysical.relaxed_chsh_bound
#print axioms OntologySeparation.LFAgencyRelaxation.SqrtTwoPhysical.relaxed_chsh_uniform
#print axioms OntologySeparation.LFAgencyRelaxation.SqrtTwoPhysical.explicit_angle_quantum_bound
#print axioms OntologySeparation.LFAgencyRelaxation.AngleOptimality.chshNumerator_le
#print axioms OntologySeparation.LFAgencyRelaxation.AngleOptimality.anchoredWitness_le_iff_relaxed_chsh
#print axioms OntologySeparation.LFAgencyRelaxation.AngleOptimality.anchoredWitness_global_optimum

#print axioms OntologySeparation.MemoryAwareness.core_inconsistent
#print axioms OntologySeparation.MemoryAwareness.memory_awareness_core_minimal
#print axioms OntologySeparation.BaumannBruknerProtocol.sqrtTwo_sq
#print axioms OntologySeparation.BaumannBruknerProtocol.computational_after_from_wigner
#print axioms OntologySeparation.BaumannBruknerProtocol.rotated_after_from_wigner
#print axioms OntologySeparation.BaumannBruknerProtocol.computational_flip_bridge
#print axioms OntologySeparation.BaumannBruknerProtocol.rotated_flip_bridge
#print axioms OntologySeparation.BaumannBruknerProtocol.exact_setting_dependence
#print axioms OntologySeparation.BaumannBruknerProtocol.flip_rates_differ
#print axioms OntologySeparation.BaumannBruknerQITSource.s_sq
#print axioms OntologySeparation.BaumannBruknerQITSource.computational_conditional
#print axioms OntologySeparation.BaumannBruknerQITSource.rotated_conditional
#print axioms OntologySeparation.BaumannBruknerQITSource.computational_branch_data
#print axioms OntologySeparation.BaumannBruknerQITSource.rotated_branch_data
#print axioms OntologySeparation.BaumannBruknerQITWigner.computational_after_qit
#print axioms OntologySeparation.BaumannBruknerQITWigner.rotated_after_qit
#print axioms OntologySeparation.BaumannBruknerQITWigner.qit_setting_dependence

#print axioms OntologySeparation.PerfectRecordTraceout.copyIsometry_isometry
#print axioms OntologySeparation.PerfectRecordTraceout.copied_entry
#print axioms OntologySeparation.PerfectRecordTraceout.marginal_entry
#print axioms OntologySeparation.PerfectRecordTraceout.cross_branch_zero
#print axioms OntologySeparation.PerfectRecordTraceout.same_branch_preserved
#print axioms OntologySeparation.PerfectRecordTraceout.inaccessible_copy_changes_coherent_state
#print axioms OntologySeparation.TwoRecordEnvironment.collapsed_entry
#print axioms OntologySeparation.TwoRecordEnvironment.one_copy_missing_state
#print axioms OntologySeparation.TwoRecordEnvironment.every_one_copy_test
#print axioms OntologySeparation.TwoRecordEnvironment.global_states_differ
#print axioms OntologySeparation.TwoRecordEnvironment.full_access_strictly_distinguishes
#print axioms OntologySeparation.QuantumAccessMonogamy.same_environment_state
#print axioms OntologySeparation.QuantumAccessMonogamy.every_environment_test
#print axioms OntologySeparation.QuantumAccessMonogamy.every_laboratory_test
#print axioms OntologySeparation.QuantumAccessMonogamy.joint_return_gap
#print axioms OntologySeparation.QuantumAccessMonogamy.disjoint_local_blind_joint_separates
#print axioms OntologySeparation.QuantumTwoObserverMonogamy.laboratory_not_separating
#print axioms OntologySeparation.QuantumTwoObserverMonogamy.environment_not_separating
#print axioms OntologySeparation.QuantumTwoObserverMonogamy.separator_requires_joint
#print axioms OntologySeparation.QuantumTwoObserverMonogamy.canSeparate_requires_laboratory
#print axioms OntologySeparation.QuantumTwoObserverMonogamy.canSeparate_requires_environment
#print axioms OntologySeparation.QuantumTwoObserverMonogamy.disjoint_policies_cannot_both_separate
#print axioms OntologySeparation.QuantumTwoObserverMonogamy.full_policy_can_separate
#print axioms OntologySeparation.FriendshipMonogamyQuantum.observerA_state
#print axioms OntologySeparation.FriendshipMonogamyQuantum.observerB_state
#print axioms OntologySeparation.FriendshipMonogamyQuantum.disjoint_single_copy_views
#print axioms OntologySeparation.FriendshipMonogamyQuantum.every_observerA_test
#print axioms OntologySeparation.FriendshipMonogamyQuantum.every_observerB_test
#print axioms OntologySeparation.FriendshipMonogamyQuantum.two_copy_access_obstruction

-- Finite stochastic conditional-local representation completeness.
#print axioms OntologySeparation.HiddenInfluence.strategyAtom_atomStrategy
#print axioms OntologySeparation.HiddenInfluence.atomStrategy_strategyAtom
#print axioms OntologySeparation.HiddenInfluence.Model.fromStrategies_toStrategies
#print axioms OntologySeparation.HiddenInfluence.StochasticModel.selected_probability
#print axioms OntologySeparation.HiddenInfluence.StochasticModel.toStrategies_ofStrategies
#print axioms OntologySeparation.HiddenInfluence.Model.stochastic_roundtrip
#print axioms OntologySeparation.HiddenInfluence.Model.fromStrategies_prob_eq_selectedMass
#print axioms OntologySeparation.HiddenInfluence.lateFromBool_surjective
#print axioms OntologySeparation.HiddenInfluence.VisibleOutcome.toOutcome_surjective
#print axioms OntologySeparation.HiddenInfluence.StochasticModel.behavior_prob_eq_factorized
#print axioms OntologySeparation.HiddenInfluence.Model.stochastic_roundtrip_weight
#print axioms OntologySeparation.HiddenInfluence.Model.stochastic_roundtrip_signaling
#print axioms OntologySeparation.ForcedSignalingTheorem2.stochastic_lower_bound
#print axioms OntologySeparation.ForcedSignalingTheorem2.stochasticWitness_matches
#print axioms OntologySeparation.ForcedSignalingTheorem2.stochasticWitness_signaling
#print axioms OntologySeparation.ForcedSignalingTheorem2.exact_forced_signaling_stochastic
#print axioms OntologySeparation.ForcedSignalingTheorem2.exact_forced_signaling_stochastic_value


-- Completion-independent forced-signaling sharpness.
#print axioms OntologySeparation.HiddenInfluenceCompletion.completion_count
#print axioms OntologySeparation.HiddenInfluenceCompletion.operationalScore_eq_marginalScore
#print axioms OntologySeparation.HiddenInfluenceCompletion.coefficient_lower_bound_all_completions
#print axioms OntologySeparation.HiddenInfluenceCompletion.optimal_completion_globally_sharp
#print axioms OntologySeparation.HiddenInfluenceCompletion.stochastic_completion_globally_sharp

-- White-noise LC4 forced-signaling robustness.
#print axioms OntologySeparation.NoisyLC4.Threshold.seed_abd_matches
#print axioms OntologySeparation.NoisyLC4.Threshold.seed_acd_matches
#print axioms OntologySeparation.NoisyLC4.Threshold.signaling_zero
#print axioms OntologySeparation.NoisyLC4.White.signaling_zero
#print axioms OntologySeparation.NoisyLC4.matches_score
#print axioms OntologySeparation.NoisyLC4.lower_bound
#print axioms OntologySeparation.NoisyLC4.Threshold.matches_noisy
#print axioms OntologySeparation.NoisyLC4.White.matches_noisy
#print axioms OntologySeparation.NoisyLC4.aboveModel_signaling
#print axioms OntologySeparation.NoisyLC4.exact_curve
#print axioms OntologySeparation.NoisyLC4.sigma_ninety_percent
#print axioms OntologySeparation.NoisyLC4.sigma_ninetyfive_percent
#print axioms OntologySeparation.NoisyLC4.exact_curve_stochastic

-- Continuous two-imperfect-record access region.
#print axioms OntologySeparation.ImperfectTwoRecordAccess.source_swap
#print axioms OntologySeparation.ImperfectTwoRecordAccess.distanceA_exact
#print axioms OntologySeparation.ImperfectTwoRecordAccess.distanceB_exact
#print axioms OntologySeparation.ImperfectTwoRecordAccess.distance_pair_exact
#print axioms OntologySeparation.ImperfectTwoRecordAccess.attainable_square
#print axioms OntologySeparation.ImperfectTwoRecordAccess.attainable_region_iff
#print axioms OntologySeparation.ImperfectTwoRecordAccess.perfect_copy_corner


-- Directional and pairwise-invisible forced-signaling Propositions 1 and 2.
#print axioms OntologySeparation.ForcedSignalingDirectional.signaling_eq_max
#print axioms OntologySeparation.ForcedSignalingDirectional.directional_bound
#print axioms OntologySeparation.ForcedSignalingDirectional.lc4_directional_lower_bound
#print axioms OntologySeparation.ForcedSignalingPropositions.proposition1
#print axioms OntologySeparation.ForcedSignalingPropositions.proposition1_A_attains
#print axioms OntologySeparation.ForcedSignalingPropositions.proposition1_D_attains
#print axioms OntologySeparation.ForcedSignalingPropositions.proposition2_A
#print axioms OntologySeparation.ForcedSignalingPropositions.proposition2_D
#print axioms OntologySeparation.ForcedSignalingPropositions.proposition2_balanced
#print axioms OntologySeparation.ForcedSignalingPropositions.pairwise_invisible_optimum
#print axioms OntologySeparation.ForcedSignalingPropositions.stochastic_signaling_eq_max
#print axioms OntologySeparation.ForcedSignalingPropositions.stochastic_directional_bound
#print axioms OntologySeparation.ForcedSignalingPropositions.stochastic_lc4_directional_lower_bound

-- Finite preferred-frame causal semantics and exact LC4 realization.
#print axioms OntologySeparation.VCausal.precedes_irrefl
#print axioms OntologySeparation.VCausal.precedes_trans
#print axioms OntologySeparation.VCausal.lightFuture_refl
#print axioms OntologySeparation.VCausal.lightFuture_trans
#print axioms OntologySeparation.VCausal.relay_inside_cone
#print axioms OntologySeparation.VCausal.LC4Layout.no_late_to_early
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.map_mass
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.reservoir_mean
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.condition_weight
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.disintegrate
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.map_single_le
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.condition_support
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.map_mean
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.bind_mean
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.complete_eq_target
#print axioms OntologySeparation.HiddenInfluence.FiniteKernel.complete_preserves_record
#print axioms OntologySeparation.VCausal.Protocol.full_behavior
#print axioms OntologySeparation.VCausal.Protocol.no_backwards_A
#print axioms OntologySeparation.VCausal.Protocol.no_backwards_D
#print axioms OntologySeparation.VCausal.backwardsTable_not_allowed
#print axioms OntologySeparation.VCausal.EarlyModel.no_backwards_A
#print axioms OntologySeparation.VCausal.EarlyModel.no_backwards_D
#print axioms OntologySeparation.VCausal.realize_strategies
#print axioms OntologySeparation.VCausal.realize_full_behavior
#print axioms OntologySeparation.VCausal.Protocol.earlyMatches
#print axioms OntologySeparation.VCausal.realizable_iff_early
#print axioms OntologySeparation.VCausal.postselection_parity
#print axioms OntologySeparation.VCausal.postselection_half
#print axioms OntologySeparation.VCausal.postselection_not_local
#print axioms OntologySeparation.VCausal.measurement_dependence_parity
#print axioms OntologySeparation.VCausal.nonsignalingBox_marginals
#print axioms OntologySeparation.ForcedSignalingVCausal.vcausal_forced_signaling_lower_bound
#print axioms OntologySeparation.ForcedSignalingVCausal.vcausal_tradeoff
#print axioms OntologySeparation.ForcedSignalingVCausal.vcausal_noise_lower_bound
#print axioms OntologySeparation.ForcedSignalingVCausal.lc4_AD_uniform
#print axioms OntologySeparation.ForcedSignalingVCausal.early_marginal_fromStrategies
#print axioms OntologySeparation.ForcedSignalingVCausal.matches_early_uniform
#print axioms OntologySeparation.ForcedSignalingVCausal.realizeLC4_weight
#print axioms OntologySeparation.ForcedSignalingVCausal.realizeLC4_behavior
#print axioms OntologySeparation.ForcedSignalingVCausal.stochastic_realization
#print axioms OntologySeparation.ForcedSignalingVCausal.witnessOn_matches
#print axioms OntologySeparation.ForcedSignalingVCausal.witnessOn_signaling
#print axioms OntologySeparation.ForcedSignalingVCausal.vcausal_exact_forced_signaling
#print axioms OntologySeparation.ForcedSignalingVCausal.vcausal_coefficient_lower_bound_all_completions
#print axioms OntologySeparation.ForcedSignalingVCausal.vcausal_optimal_completion_globally_sharp

#print axioms OntologySeparation.VCausal.backwards_marginal_not_realizable

-- Timing interventions and collectible recipient records.
#print axioms OntologySeparation.VCausal.lightFuture_iff
#print axioms OntologySeparation.VCausal.apex_plus
#print axioms OntologySeparation.VCausal.apex_minus
#print axioms OntologySeparation.VCausal.apex_receives
#print axioms OntologySeparation.VCausal.apex_before_collection
#print axioms OntologySeparation.VCausal.collectible_iff_apex
#print axioms OntologySeparation.VCausal.collectible_criterion
#print axioms OntologySeparation.VCausal.segment_obstruction
#print axioms OntologySeparation.VCausal.not_collectible_of_between
#print axioms OntologySeparation.VCausal.Collectible.mono
#print axioms OntologySeparation.VCausal.recipients_A_dichotomy
#print axioms OntologySeparation.VCausal.recipients_D_dichotomy
#print axioms OntologySeparation.VCausal.collectible_A_pinned_pair
#print axioms OntologySeparation.VCausal.collectible_D_pinned_pair
#print axioms OntologySeparation.VCausal.TimingProtocol.delayC_preserves_ABD
#print axioms OntologySeparation.VCausal.TimingProtocol.delayB_preserves_ACD
#print axioms OntologySeparation.VCausal.TimingProtocol.completeTarget_runC
#print axioms OntologySeparation.VCausal.TimingProtocol.completeTarget_runB
#print axioms OntologySeparation.ForcedSignalingLayouts.minimal_lc4
#print axioms OntologySeparation.ForcedSignalingLayouts.minimal_order
#print axioms OntologySeparation.ForcedSignalingLayouts.minimal_A_collectible
#print axioms OntologySeparation.ForcedSignalingLayouts.minimal_D_collectible
#print axioms OntologySeparation.ForcedSignalingLayouts.minimal_margins
#print axioms OntologySeparation.ForcedSignalingLayouts.restoration_lc4
#print axioms OntologySeparation.ForcedSignalingLayouts.restoration_order
#print axioms OntologySeparation.ForcedSignalingLayouts.restoration_A_collectible
#print axioms OntologySeparation.ForcedSignalingLayouts.restoration_D_collectible
#print axioms OntologySeparation.ForcedSignalingLayouts.restoration_threshold_rounding
#print axioms OntologySeparation.ForcedSignalingCollectibility.both_collectible_context
#print axioms OntologySeparation.ForcedSignalingCollectibility.signaling_attained
#print axioms OntologySeparation.ForcedSignalingCollectibility.vcausal_forced_superluminal_signal
#print axioms OntologySeparation.ForcedSignalingCollectibility.minimal_both_collectible
#print axioms OntologySeparation.ForcedSignalingCollectibility.restoration_both_collectible
#print axioms OntologySeparation.ForcedSignalingPinned.pinned_BD
#print axioms OntologySeparation.ForcedSignalingPinned.pinned_CD
#print axioms OntologySeparation.ForcedSignalingPinned.pinned_AB
#print axioms OntologySeparation.ForcedSignalingPinned.pinned_AC
#print axioms OntologySeparation.ForcedSignalingPinned.pinned_projection
#print axioms OntologySeparation.ForcedSignalingTiming.protocol_ABD
#print axioms OntologySeparation.ForcedSignalingTiming.protocol_ACD
#print axioms OntologySeparation.ForcedSignalingTiming.ConnectedMatches.blind_matches
#print axioms OntologySeparation.ForcedSignalingTiming.timing_forced_superluminal_signal
#print axioms OntologySeparation.LC4FullDistribution.quantum_abd
#print axioms OntologySeparation.LC4FullDistribution.quantum_acd
#print axioms OntologySeparation.ForcedSignalingTimingExtension.target_ABD_matches
#print axioms OntologySeparation.ForcedSignalingTimingExtension.target_ACD_matches
#print axioms OntologySeparation.ForcedSignalingTimingExtension.delayC_quantum
#print axioms OntologySeparation.ForcedSignalingTimingExtension.delayB_quantum
#print axioms OntologySeparation.ForcedSignalingTimingExtension.delayC_keeps_existing_records
#print axioms OntologySeparation.ForcedSignalingTimingExtension.delayB_keeps_existing_records
#print axioms OntologySeparation.ForcedSignalingTimingExtension.quantumTiming_runC
#print axioms OntologySeparation.ForcedSignalingTimingExtension.quantumTiming_runB
#print axioms OntologySeparation.ForcedSignalingTimingExtension.quantumTiming_connected
#print axioms OntologySeparation.ForcedSignalingTimingExtension.attaining_timing_extension
#print axioms OntologySeparation.ForcedSignalingAccessible.pinned_A_subsets
#print axioms OntologySeparation.ForcedSignalingAccessible.pinned_D_subsets
#print axioms OntologySeparation.ForcedSignalingAccessible.zero_accessible_A
#print axioms OntologySeparation.ForcedSignalingAccessible.zero_accessible_D

-- Additional review obligations: exact finite scope and geometry.
#print axioms OntologySeparation.ForcedSignalingVCausal.conditional_local_nonsignaling_exclusion
#print axioms OntologySeparation.VCausal.SupportedProtocol.full_behavior
#print axioms OntologySeparation.ForcedSignalingCollectibility.noisy_collectible_signal
#print axioms OntologySeparation.ForcedSignalingCollectibility.restoration_ninety_percent_signal
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.precedes_duration
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.minimal_duration_lc4
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.minimal_duration_order
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.minimal_duration_cross_events
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.minimal_collector_delay
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.minimal_duration_collectible
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.boost_lightFuture
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.boost_collectible
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.restoration_boost_collectible
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.restoration_frame_iff
#print axioms OntologySeparation.ForcedSignalingGeometryRobustness.restoration_frame_order_iff
#print axioms OntologySeparation.ForcedSignaling.physical_main

#print axioms OntologySeparation.ForcedSignalingAccessible.zero_accessible_A_of_blind_pair_not_collectible
#print axioms OntologySeparation.ForcedSignalingAccessible.zero_accessible_D_of_blind_pair_not_collectible

#print axioms OntologySeparation.ForcedSignalingAccessibleOptimum.recordParties_complete
#print axioms OntologySeparation.ForcedSignalingAccessibleOptimum.proper_encoding
#print axioms OntologySeparation.ForcedSignalingAccessibleOptimum.full_encoding
#print axioms OntologySeparation.ForcedSignalingAccessibleOptimum.accessible_nonnegative
#print axioms OntologySeparation.ForcedSignalingAccessibleOptimum.accessible_invisible
#print axioms OntologySeparation.ForcedSignalingAccessibleOptimum.proposition2_layout_minimum
#print axioms OntologySeparation.ForcedSignalingAccessibleOptimum.stochastic_layout_minimum
