import OntologySeparation.Operational.VCausalTiming

namespace OntologySeparation.VCausal
noncomputable section
open scoped BigOperators
open HiddenInfluence

private theorem map_as_mean {α β : Type} [Fintype α] [Fintype β] [DecidableEq β]
    (d : FiniteDistribution α) (f : α → β) (b : β) :
    (FiniteKernel.map d f).mass b = ∑ a, d.mass a * (if f a = b then 1 else 0) := by
  simp [FiniteKernel.map_mass, mul_ite]

private theorem reconstruct_condition {α β γ : Type} [Fintype α] [Fintype β] [Fintype γ]
    [DecidableEq α] [DecidableEq β] [DecidableEq γ] [Inhabited α]
    (d : FiniteDistribution α) (f : α → β) (r : β) (choose : α → γ) (assemble : γ → α)
    (hr : (FiniteKernel.map d f).mass r ≠ 0)
    (ha : ∀ a, f a = r → assemble (choose a) = a) (o : α) :
    (FiniteKernel.map (FiniteKernel.map (FiniteKernel.condition d f r) choose) assemble).mass o =
      (FiniteKernel.condition d f r).mass o := by
  rw [map_as_mean, FiniteKernel.map_mean]
  calc
    _ = ∑ a, (FiniteKernel.condition d f r).mass a * (if a = o then 1 else 0) := by
      apply Finset.sum_congr rfl
      intro a _
      by_cases h : (FiniteKernel.condition d f r).mass a = 0
      · simp [h]
      · rw [ha a (FiniteKernel.condition_support d f r a hr h)]
    _ = _ := by simp

/-- A delayed party samples its own component of the target conditional. The
other outcome and the early record have already been generated by `p`. -/
def TimingProtocol.completeTarget {order : EarlyOrder} {Ω : Type} [Fintype Ω]
    (p : Protocol order Ω) (target : Early → Bool → Bool → FiniteDistribution VisibleOutcome)
    [Inhabited VisibleOutcome] : TimingProtocol p where
  delayedC _ e y z r := FiniteKernel.map (FiniteKernel.condition (target e y z) abdRecord r) VisibleOutcome.c
  delayedB _ e y z r := FiniteKernel.map (FiniteKernel.condition (target e y z) acdRecord r) VisibleOutcome.b

theorem TimingProtocol.completeTarget_runC {order : EarlyOrder} {Ω : Type} [Fintype Ω]
    (p : Protocol order Ω) (target : Early → Bool → Bool → FiniteDistribution VisibleOutcome)
    [Inhabited VisibleOutcome] (e : Early) (y z : Bool)
    (h : ∀ r, (FiniteKernel.map (p.run e y z) abdRecord).mass r =
      (FiniteKernel.map (target e y z) abdRecord).mass r) (o : VisibleOutcome) :
    ((completeTarget p target).runC e y z).mass o = (target e y z).mass o := by
  rw [← FiniteKernel.complete_eq_target (p.run e y z) (target e y z) abdRecord h o]
  unfold runC FiniteKernel.complete
  rw [FiniteKernel.bind_mass, FiniteKernel.bind_mass]
  unfold Protocol.run
  rw [FiniteKernel.map_mean]
  apply Finset.sum_congr rfl
  intro ω _
  by_cases hω : p.shared.mass ω = 0
  · simp [hω]
  · congr 1
    apply reconstruct_condition
    · have hm := FiniteKernel.map_single_le p.shared
        (fun ω => abdRecord ((p.table ω e).visible y z)) ω
      have he : (FiniteKernel.map (p.run e y z) abdRecord).mass
          (abdRecord ((p.table ω e).visible y z)) =
          (FiniteKernel.map p.shared (fun ω => abdRecord ((p.table ω e).visible y z))).mass
            (abdRecord ((p.table ω e).visible y z)) := by
        rw [map_as_mean, Protocol.run, FiniteKernel.map_mean, map_as_mean]
      rw [← he, h] at hm
      exact ne_of_gt (lt_of_lt_of_le (lt_of_le_of_ne (p.shared.nonneg ω) (Ne.symm hω)) hm)
    · intro a ha
      cases a; simp_all [abdRecord, withC]

theorem TimingProtocol.completeTarget_runB {order : EarlyOrder} {Ω : Type} [Fintype Ω]
    (p : Protocol order Ω) (target : Early → Bool → Bool → FiniteDistribution VisibleOutcome)
    [Inhabited VisibleOutcome] (e : Early) (y z : Bool)
    (h : ∀ r, (FiniteKernel.map (p.run e y z) acdRecord).mass r =
      (FiniteKernel.map (target e y z) acdRecord).mass r) (o : VisibleOutcome) :
    ((completeTarget p target).runB e y z).mass o = (target e y z).mass o := by
  rw [← FiniteKernel.complete_eq_target (p.run e y z) (target e y z) acdRecord h o]
  unfold runB FiniteKernel.complete
  rw [FiniteKernel.bind_mass, FiniteKernel.bind_mass]
  unfold Protocol.run
  rw [FiniteKernel.map_mean]
  apply Finset.sum_congr rfl
  intro ω _
  by_cases hω : p.shared.mass ω = 0
  · simp [hω]
  · congr 1
    apply reconstruct_condition
    · have hm := FiniteKernel.map_single_le p.shared
        (fun ω => acdRecord ((p.table ω e).visible y z)) ω
      have he : (FiniteKernel.map (p.run e y z) acdRecord).mass
          (acdRecord ((p.table ω e).visible y z)) =
          (FiniteKernel.map p.shared (fun ω => acdRecord ((p.table ω e).visible y z))).mass
            (acdRecord ((p.table ω e).visible y z)) := by
        rw [map_as_mean, Protocol.run, FiniteKernel.map_mean, map_as_mean]
      rw [← he, h] at hm
      exact ne_of_gt (lt_of_lt_of_le (lt_of_le_of_ne (p.shared.nonneg ω) (Ne.symm hω)) hm)
    · intro a ha
      cases a; simp_all [acdRecord, withB]

end
end OntologySeparation.VCausal
